networks:
  reverse-proxy:
    external: true

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.0
    container_name: lidarr
    user: ${UID}:${GID}
    networks:
      - reverse-proxy
    volumes:
      - ~/home-server/lidarr/config:/config:rw
      - /mnt/storage/downloads:/downloads:rw
      - /mnt/storage/media/music:/music:rw
    environment:
      PGID: ${GID}
      PUID: ${UID}
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr.entrypoints: websecure
      traefik.http.routers.lidarr.rule: Host(`lidarr.${DOMAIN_NAME}`) || Host(`music.${DOMAIN_NAME}`)
      traefik.http.routers.lidarr.middlewares: chain-authentik@file
      traefik.http.services.lidarr.loadbalancer.server.port: 8686
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8686/ping"]
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
