networks:
  reverse-proxy:
    external: true

services:
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:2.3.0
    container_name: uptime-kuma
    # user: ${UID}:${GID}
    networks:
      - reverse-proxy
    volumes:
      - ~/home-server/uptime-kuma:/app/data:rw
    labels:
      traefik.enable: true
      traefik.http.routers.uptime-kuma.entrypoints: websecure
      traefik.http.routers.uptime-kuma.rule: Host(`uptime.${DOMAIN_NAME}`) || Host(`kuma.${DOMAIN_NAME}`)
      traefik.http.routers.uptime-kuma.middlewares: chain-authentik@file
      traefik.http.services.uptime-kuma.loadbalancer.server.port: 3001
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://uptime-kuma:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
