networks:
  reverse-proxy:
    external: true

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.10.2
    container_name: node-exporter
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '0.01'
          memory: 16M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    # user: ${UID}:${GID}
    pid: host
    networks:
      - reverse-proxy
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--path.udev.data=/rootfs/run/udev/data'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
