networks:
  reverse-proxy:
    external: true

services:
  node-exporter:
    image: docker.io/prom/node-exporter:v1.10.2
    container_name: node-exporter
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '0.01'
          memory: 16M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    # user: ${UID}:${GID}
    networks:
      - reverse-proxy
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/) 
      - --collector.filesystem.ignored-fs-types=^(tmpfs|autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
