networks:
  reverse-proxy:
    external: true

services:
  memos:
    image: ghcr.io/usememos/memos:0.26.1
    container_name: memos
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          cpus: '0.01'
          memory: 16M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://memos:5230"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 5s
    networks:
      - reverse-proxy
    volumes:
      - ~/home-server/memos:/var/opt/memos:rw
    labels:
      traefik.enable: true
      traefik.http.routers.memos.entrypoints: websecure
      traefik.http.routers.memos.rule: Host(`memos.${DOMAIN_NAME}`)
      traefik.http.routers.memos.middlewares: chain-authentik@file
      traefik.http.services.memos.loadbalancer.server.port: 5230
