networks:
  reverse-proxy:
    external: true

services:
  tabby:
    image: ghcr.io/tabbyml/tabby:0.32.0
    container_name: tabby
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
          # devices:
          #   - driver: intel
          #     count: all
          #     capabilities: [gpu]
          #   - driver: nvidia
          #     count: 1
          #     capabilities: [gpu]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    command:
      - serve
      # - --device=metal
      - --model=StarCoder-1B
      - --chat-model=Qwen2-1.5B-Instruct
    networks:
      - reverse-proxy
    volumes:
      - ~/home-server/tabby:/data:rw
    labels:
      traefik.enable: true
      traefik.http.routers.tabby.entrypoints: websecure
      traefik.http.routers.tabby.rule: Host(`tabby.${DOMAIN_NAME}`) || Host(`ai.${DOMAIN_NAME}`)
      traefik.http.routers.tabby.middlewares: chain-no-auth@file
      traefik.http.services.tabby.loadbalancer.server.port: 8080
