networks:
  reverse-proxy:
    external: true

services:
  actual-budget:
    image: ghcr.io/actualbudget/actual:26.4.0
    container_name: actual-budget
    networks:
      - reverse-proxy
    volumes:
      - ~/home-server/actual-budget/data:/data:rw
    environment:
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.actual-budget.entrypoints: websecure
      traefik.http.routers.actual-budget.rule: Host(`actual.${DOMAIN_NAME}`) || Host(`budget.${DOMAIN_NAME}`)
      traefik.http.routers.actual-budget.middlewares: chain-actual-budget@file
      traefik.http.services.actual-budget.loadbalancer.server.port: 5006
    healthcheck:
      disable: true
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
