networks:
  reverse-proxy:
    external: true

services:
  adguardhome:
    image: docker.io/adguard/adguardhome:v0.107.74
    container_name: adguardhome
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - reverse-proxy
    volumes:
      - ~/home-server/adguardhome/conf:/opt/adguardhome/conf:rw
      - ~/home-server/adguardhome/work:/opt/adguardhome/work:rw
    labels:
      traefik.enable: true
      traefik.http.routers.adguardhome.entrypoints: websecure
      traefik.http.routers.adguardhome.rule: Host(`adguard.${DOMAIN_NAME}`) || Host(`adguardhome.${DOMAIN_NAME}`)
      traefik.http.routers.adguardhome.middlewares: chain-no-auth@file
      traefik.http.services.adguardhome.loadbalancer.server.port: 80
    healthcheck:
      test: ["CMD", "wget", "--spider", "localhost:80"]
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.01'
          memory: 128M
