networks:
  reverse-proxy:
    external: true

services:
  dozzle:
    image: docker.io/amir20/dozzle:v10.0.0
    container_name: dozzle
    networks:
      - reverse-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.dozzle.entrypoints: websecure
      traefik.http.routers.dozzle.rule: Host(`dozzle.${DOMAIN_NAME}`)
      traefik.http.routers.dozzle.middlewares: chain-authentik@file
      traefik.http.services.dozzle.loadbalancer.server.port: 8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://dozzle:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
        reservations:
          cpus: '0.01'
          memory: 128M
