networks:
  reverse-proxy:
    external: true

services:
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:2.14.1
    container_name: zigbee2mqtt
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - reverse-proxy
    volumes:
      - ~/home-server/zigbee2mqtt/data:/app/data:rw
      - /run/udev:/run/udev:ro
    environment:
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.zigbee2mqtt.entrypoints: websecure
      traefik.http.routers.zigbee2mqtt.rule: Host(`zigbee.${DOMAIN_NAME}`) || Host(`z2m.${DOMAIN_NAME}`)
      traefik.http.routers.zigbee2mqtt.middlewares: chain-authentik@file
      traefik.http.services.zigbee2mqtt.loadbalancer.server.port: 8080
    healthcheck:
      disable: true
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
