networks:
  reverse-proxy:
    external: true

services:
  dozzle:
    image: docker.io/amir20/dozzle:v10.6.7
    container_name: dozzle
    networks:
      - reverse-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.dozzle.entrypoints: websecure
      traefik.http.routers.dozzle.rule: Host(`dozzle.${DOMAIN_NAME}`)
      traefik.http.routers.dozzle.middlewares: chain-authentik@file
      traefik.http.services.dozzle.loadbalancer.server.port: 8080
    healthcheck:
      disable: true
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
        reservations:
          cpus: '0.01'
          memory: 128M
