networks:
  reverse-proxy:
    external: true

services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli:2.17.2
    container_name: tautulli
    user: ${UID}:${GID}
    networks:
      - reverse-proxy
    volumes:
      - ~/home-server/plex/config:/plex/config:ro
      - ~/home-server/tautulli/config:/config:rw
      - ~/home-server/tautulli/logs:/logs:rw
    environment:
      PGID: ${GID}
      PUID: ${UID}
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.tautulli.entrypoints: websecure
      traefik.http.routers.tautulli.rule: Host(`tautulli.${DOMAIN_NAME}`)
      traefik.http.routers.tautulli.middlewares: chain-authentik@file
      traefik.http.services.tautulli.loadbalancer.server.port: 8181
      homepage.group: Media
      homepage.name: Tautulli
      homepage.icon: tautulli.png
      homepage.href: https://tautulli.${DOMAIN_NAME}
      homepage.description: Plex monitoring
      homepage.widget.type: tautulli
      homepage.widget.url: https://tautulli.${DOMAIN_NAME}
      homepage.widget.key: ${TAUTULLI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://tautulli:8181/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 256M

