version: "3.9"
services:
  # https://hub.docker.com/r/factoriotools/factorio
  factorio:
    image: factoriotools/factorio:1.1.106@sha256:4391b9c05d97409a059e1e54b23bc353d6e05d725b5dcf8c72f8b3a8d38ca852
    container_name: factorio
    restart: unless-stopped
    cpus: 1
    mem_limit: 1024m
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      #- LOAD_LATEST_SAVE=false
      #- SAVE_NAME=<savename>
    volumes:
      - ${USER_DIR}/factorio:/factorio
    ports:
      - 34197:34197/udp
      #- 27015:27015/tcp # RCON optional
    labels:
    - diun.enable=true
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default