services:
  # https://github.com/felddy/foundryvtt-docker
  foundry:
    image: felddy/foundryvtt:12.330.0@sha256:3f274dfd929a2ed4dea21ff66f4eb9bfcc90c2e72e12e835f19b80535a33f9d0
    container_name: foundry
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
    - TZ=${TZ}
    - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
    - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
    - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_KEY}
    volumes:
    - ${USER_DIR}/foundry:/data
    expose:
    - 30000
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
