@startuml Radarr

participant Radarr #lightblue
participant Prowlarr #orange
participant NZBGeek #white
participant SABnzbd #yellow
participant newsdemon.com #blackø
participant Bazarr #purple
participant Provider
participant Plex #orange

Radarr -> Prowlarr: Movie request
Prowlarr -> NZBGeek: Search indexer
NZBGeek -> Prowlarr: Return grab
Prowlarr -> Radarr: Return grab
Radarr -> SABnzbd: Send grab
SABnzbd -> newsdemon.com: Download request
newsdemon.com -> SABnzbd: /downloads/usenet/incomplete/
SABnzbd -> Radarr: /downloads/usenet/complete/
Radarr -> Bazarr: /media/movies/**<title>**
Bazarr -> Provider: Request subtitles
Provider -> Bazarr: Subtitles file
Bazarr -> Radarr: Subtitle alongside file
Radarr -> Plex: /media/movies/

@enduml
