name: Terraform OCI

on:
  push:
    branches:
      - main
    paths:
      - "_terraform/oci/**"
  workflow_dispatch:

jobs:
  terraform-oci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: _terraform/oci
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: "~> 1.15"

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan -out=tfplan

      - name: Apply
        run: terraform apply tfplan
